### ISSUE TITLE
UserAdmin.CreateUserPage threw an exception.

### ISSUE THREAD

**Issue by per-samuelsson** [StarcounterApps/UserAdmin#52]
Noticed two log entries in a live environment today where the following occurred:

```
[13:57:41, Error, Starcounter.Host (default)]
System.TypeInitializationException: The type initializer for 'UserAdmin.CreateUserPage' threw an exception.
   at UserAdmin.CreateUserPage..ctor()
   at UserAdmin.SystemUsersHandlers.<>c__DisplayClass0_0.<Register>b__1(Request request) in C:\code-backup\UserAdmin\src\UserAdmin\Api\SystemUsersHandlers.cs:line 29
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
TypeName=UserAdmin.CreateUserPage
HResult=-2146233036
---> System.MissingMethodException: Method not found: 'Void Starcounter.Templates.Template.set_ClassName(System.String)'.
   at Smorgasbord.PropertyMetadata.PropertyMetadataPage.JsonByExample.Schema..ctor()
   at UserAdmin.CreateUserPage.JsonByExample.Schema..ctor() in C:\code-backup\UserAdmin\src\UserAdmin\obj\x64\Debug\ViewModels\Administrator\CreateUserPage-1004.json.g.cs:line 0
   at UserAdmin.CreateUserPage..cctor() in C:\code-backup\UserAdmin\src\UserAdmin\obj\x64\Debug\ViewModels\Administrator\CreateUserPage-1004.json.g.cs:line 0
HResult=-2146233069
```

Version of Starcounter: `Version: 2.3.0.5523`

Any ideas?

cc @warpech @chrhol @miyconst @andwah 

cc @atifwaqar

**Comment by warpech** [comment]
I don't have good idea what does this stack trace mean (@chrhol please help).

Just a general info UserAdmin version 4.0.3 and older use https://github.com/Smorgasbord-Development/PropertyMetadata DLL from NuGet.

Starting from the code currently in the `develop` branch, PropertyMetadata is included directly in the app, not referenced as a separate DLL.

**Comment by warpech** [comment]
@chrhol ping

**Comment by warpech** [comment]
Most probably this problem was fixed on `develop` with https://github.com/StarcounterApps/UserAdmin/pull/44. @un-tone could you pls check that?

**Comment by un-tone** [comment]
Yes, it was fixed. Closing the issue as done.
